[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "financial-statements-rag"
authors = [
  { name = "TJ Maynes", email = "tj@tjmaynes.com" },
]
description = "RAG pipeline for analyzing financial statements"
readme = "README.md"
requires-python = ">=3.14"
dynamic = ["version"]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "arq",
    "fastapi",
    "jinja2",
    "langchain-community",
    "langchain-core",
    "langchain-openai",
    "langgraph",
    "pgvector",
    "psycopg[binary]",
    "pypdf",
    "python-multipart",
    "redis",
    "uvicorn",
]

[project.optional-dependencies]
dev = [
    "httpx2",
    "mypy==1.13.0",
    "pytest==8.3.4",
    "ruff==0.8.3"
]

[tool.hatch.build.targets.wheel]
packages = ["financial_statements_rag"]

[tool.hatch.version]
path = "financial_statements_rag/version.py"

[project.scripts]
financial-statements-rag = "financial_statements_rag.main:main"

[tool.pytest.ini_options]
pythonpath = "."

[tool.mypy]
python_version = "3.14"
warn_return_any = true
warn_unused_configs = true
